# Generated by Django 3.0.4 on 2020-03-12 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['run_time'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('date_posted', models.DateTimeField()),
                ('logo_url', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(max_length=100)),
                ('day_scraped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scrape')),
            ],
        ),
    ]
